before_cache:
  - rm -rf $HOME/.m2/repository/Bobbin
cache:
  directories:
    - $HOME/.m2/repository
git:
  quiet: true
jdk: openjdk11
language: java
script: mvn clean test javadoc:test-javadoc jacoco:report -B
